### ISSUE TITLE
Save permalink history

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms-django#226] opened 2019-11-22 10:48 UTC
When the permalink of an existing page is changed, we should keep the old permalink in our database and if it's called, it should navigate to the new page.

**Comment by timoludwig** [comment] 2019-11-22 10:55
This is a duplicate of #119. With our current model structure, we already have that database (because we use versions for page translations and when the permalink changes, we store a new version of the translation).

**Closed by timoludwig** 2019-11-22 10:55 UTC
