### ISSUE TITLE
Add CMS "expert" modus for user/regions

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/cms-django#500] opened 2020-09-25 13:56 UTC
### Motivation
The region team requested a special mode for users to reduce their function view and only enable them, if they are considered experienced enough. These functionalities are:
- Live Content
- DoNotTranslate
- Recurring Events
... More to come.

### Proposed Solution
Add a special user permission, which is deactivated for all user by default. Grant the permission to specific user after a "expert" workshop.

### Alternatives
Add an additional option on the region level.

### Additional Context
...

**Comment by timoludwig** [comment] 2020-09-25 13:58
Duplicate of #499

**Closed by timoludwig** 2020-09-25 13:58 UTC
Labels: enhancement, feature
