### ISSUE TITLE
Adjust static path to fix icon loading.

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/cms-django#418] opened 2020-06-19 14:01 UTC
![grafik](https://user-images.githubusercontent.com/15608678/85140673-dbe61d00-b245-11ea-97e6-3d6d83d8d9be.png)
As be seen in the screenshot the TinyMCE isn't loading the icons correctly. I think that happend when we changed the project structure to be compliant with Sphinx.

**Comment by timoludwig** [comment] 2020-06-26 18:45
I cannot reproduce this issue on my two develop environments, but only on my virtual machine where I installed Ubuntu 20.04 and run the system with Python3.8.
As we currently don't officially support Python3.8 and the problem does only exist when applying the compression, I'd say we can close this issue.
You won't experience this problem anymore after PR #423 is merged.

**Closed by timoludwig** 2020-06-26 18:45 UTC
Labels: bug, prio: medium
